In [1]:
import numpy as np
print(np.__version__)
arr1=np.array(12)
print(arr1)

1.26.4
12


In [2]:
import numpy as np
a=np.array(42)
print(a.ndim)
print(a.dtype)

0
int32


In [4]:
import numpy
marr=numpy.array([1,3,4,5])
print(marr)
for i in marr:
    print(i+2)

[1 3 4 5]
3
5
6
7


In [5]:
import numpy as np
marr2=np.array([1,2,3,4,5])
print(marr2)

[1 2 3 4 5]


In [8]:
marr3=np.array({1,2,3,4})
print(marr3)
print(type(marr3))
print(type(marr2)==type(marr3))

{1, 2, 3, 4}
<class 'numpy.ndarray'>
True


In [9]:
mr={2,2,3,4}
print(mr)
marr4=np.array((1,2,3,4))
print(marr4)

{2, 3, 4}
[1 2 3 4]


In [10]:
marr5=np.array(['a','b'])
print(marr5)

['a' 'b']


In [11]:
marr6={'brand':'Toyota','model':'RAV4','year':2020}
print(marr6)
print(type(marr6))
marr7=np.array(marr6)
print(marr7)
print(type(marr7))

{'brand': 'Toyota', 'model': 'RAV4', 'year': 2020}
<class 'dict'>
{'brand': 'Toyota', 'model': 'RAV4', 'year': 2020}
<class 'numpy.ndarray'>


In [16]:
import numpy as np
marr=np.array([[1,2,3],[4,5,6]])
print(marr)
print(marr[1,2])

[[1 2 3]
 [4 5 6]]
6


In [13]:
print(marr[0,1])

2


In [14]:
print(marr[1,1])

5


In [17]:
print(marr[0,2])

3


In [18]:
print(marr[0,0:-1])

[1 2]


In [21]:
import numpy as np
marr=np.array([[[1,2],[4,5]],[[1,3],[5,6]]])
marr1=marr.copy()
marr2=marr.view()

In [23]:
print(marr)

[[[1 2]
  [4 5]]

 [[1 3]
  [5 6]]]


In [24]:
print(marr1)

[[[1 2]
  [4 5]]

 [[1 3]
  [5 6]]]


In [25]:
print(marr2)
print(type(marr2))

[[[1 2]
  [4 5]]

 [[1 3]
  [5 6]]]
<class 'numpy.ndarray'>


In [26]:
print(marr2[1,1])
print(marr2[0,0])
print(marr2[0,1])

[5 6]
[1 2]
[4 5]


In [27]:
print(marr.shape)
for x in marr:
    print(x)
marr3=np.concatenate((marr,marr1))

(2, 2, 2)
[[1 2]
 [4 5]]
[[1 3]
 [5 6]]


In [28]:
print(marr3)

[[[1 2]
  [4 5]]

 [[1 3]
  [5 6]]

 [[1 2]
  [4 5]]

 [[1 3]
  [5 6]]]


In [29]:
import numpy as np
marr=np.array([1,2,3,4,5,4,])
x=np.where(marr==5)
print(x)
print(np.sort(marr))

(array([4], dtype=int64),)
[1 2 3 4 4 5]


In [30]:
from numpy import random
x=random.randint(10)
print(x)
y=random.randint(10,size=(3,5))
print(y)
print(y[2,3])

1
[[1 1 7 6 6]
 [7 9 9 0 3]
 [9 4 7 3 5]]
3


In [32]:
x=np.array([1,3,5,6,9])
y=np.array([2,4,6,8,10])
print(type(x))
print(type(y))
print(x[0],x[1])
print(y[3],y[4])

# 建立二維陣列
z=np.array([[1,3,5],[2,4,6]])
print(z[0,0],z[1,1])
z[1,1]=17
print(z)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
1 3
8 10
1 4
[[ 1  3  5]
 [ 2 17  6]]
