In [2]:
import numpy as np
print(np.__version__) # 顯示Numpy版本

arr1=np.array(12) #　填入單一變數，建立0維陣列

1.26.4


In [2]:
import numpy as np
a= np.array(42)
print(a.ndim) # 輸出陣列維度
print(a.dtype) # 輸出元素資料類型

0
int32
<class 'numpy.ndarray'>


In [15]:
import numpy
marr=numpy.array([1,3,5]) #建立ndarray obeject多維度陣列物件
print('marr=',marr)
print('marr type=',type(marr))
import numpy as np
marr2=numpy.array([1,2,3,4,5])
print('marr2=',marr2)
marr3=np.array((2,4,6))
print('marr3=',marr3)
marr4=np.array([1,2,3,4,5])
print('marr4=',marr4)

marr= [1 3 5]
marr type= <class 'numpy.ndarray'>
marr2= [1 2 3 4 5]
marr3= [2 4 6]
marr4= [1 2 3 4 5]


In [17]:
import numpy as np
marr=np.array([[1,2,3],[4,5,6]])
print('marr=',marr)
print('marr[1,2]=',marr[1,2]) # 輸出第一行第二列變數行(! 行列數從0開始)
print('marr type[1,-1]=',type(marr[1,-1]))
print('marr[1:2,1:2]=',marr[1:2,1:2])

marr= [[1 2 3]
 [4 5 6]]
marr[1,2]= 6
marr type[1,-1]= <class 'numpy.int32'>
marr[1:2,1:2]= [[5]]


In [6]:
import numpy as np
marr=np.array([[[1,2],[4,5]],[[1,3],[5,6]]])
marr1=marr.copy()
marr2=marr.view()
print('marr_shape:',marr.shape) # 輸出維度大小
for x in marr:
    print('x in marr:',x)
marr3=np.concatenate((marr,marr1))
print('marr:',marr)
print('marr1:',marr1)
print('marr2:',marr2)
print('marr3:',marr3)

marr_shape: (2, 2, 2)
x in marr: [[1 2]
 [4 5]]
x in marr: [[1 3]
 [5 6]]
marr: [[[1 2]
  [4 5]]

 [[1 3]
  [5 6]]]
marr1: [[[1 2]
  [4 5]]

 [[1 3]
  [5 6]]]
marr2: [[[1 2]
  [4 5]]

 [[1 3]
  [5 6]]]
marr3: [[[1 2]
  [4 5]]

 [[1 3]
  [5 6]]

 [[1 2]
  [4 5]]

 [[1 3]
  [5 6]]]


In [14]:
import numpy as np
marr=np.array([1,2,3,4,5,4,4])
print('marr升序排列=',np.sort(marr))
x=np.where(marr==5) # 查找marr中等於5的元素位置,將結果賦值給x
print('x=',x)

from numpy import random
x=random.randint(100) # 生成一個範圍在0-100間的隨機整,包含0但不包含100
print('x=',x)
y=random.randint(100,size=(3,5))#生成一個3*5的二維隨機整數陣列,賦值給y
print('y=',y)

marr升序排列= [1 2 3 4 4 4 5]
x= (array([4], dtype=int64),)
x= 40
y= [[ 1 43 44 83 59]
 [14 98 55 29 86]
 [85 14 63 15 86]]
